import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClientProvider } from './redux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Redux Toolkit Essentials Tutorial',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<ClientProvider>
				<body className={inter.className}>
					<nav className='flex h-32 w-full items-center justify-center bg-violet-600 text-4xl font-extrabold'>
						<h1>Redux Essentials Example</h1>
					</nav>
					{children}
				</body>
			</ClientProvider>
		</html>
	)
}
